### ISSUE TITLE
Error 38&39 and 78

### ISSUE THREAD

**Issue by ErrinRF** [AstrorEnales/blender_magicavoxel#7] opened 2022-07-12 13:08 UTC
Hi I get this error while trying to import voxel file with material per color
![55](https://user-images.githubusercontent.com/109153694/178497157-18c34d56-7551-42de-9228-18407e1b6981.jpg)

**Comment by AstrorEnales** [comment] 2022-07-12 14:19
@ErrinRF Thank you very much for reporting this issue. Can you verify which version of the addon you have installed in the blender addon settings? I added a fix for this material mode in the newest release v1.3.0 which should have fixed this issue. Otherwise, i will take a look.

**Comment by ErrinRF** [comment] 2022-07-12 15:27
I'm working with latest version but I found the problem and solution. It simply doesn't work with exported .vox files and works fine with normal save .vox files in MV 99.6.4.

**Comment by AstrorEnales** [comment] 2022-07-12 15:32
Interesting, i actually never tried it with exported files. Glad that it works with normal saved ones! Nonetheless, i will check out what the issue is with exported files.

**Comment by AstrorEnales** [comment] 2022-07-12 15:37
I just opened my material test file and used the export function. When looking at the file, all information except the most basic voxel information are completely removed. I would recommend always using the normal save function then.
Will still check out why the material mode has a problem with these minimal files.

**Closed as completed** 2024-02-09 09:59 UTC
Labels: bug
