### ISSUE TITLE
UV unwrap fills several faces with black

### ISSUE THREAD

**Issue by drca234** [AstrorEnales/blender_magicavoxel#12] opened 2024-06-24 20:50 UTC
When importing a goblin vox, I am getting some coloration issues on the top, bottom, and back of the imported model. The following screenshot is of the view in Magica Voxel, and the ones after are front and back of the vox after import into Blender:
![image](https://github.com/AstrorEnales/blender_magicavoxel/assets/16767517/32f02c14-bc39-416b-89a6-d9c0cdbde70f)
![image](https://github.com/AstrorEnales/blender_magicavoxel/assets/16767517/e8201e04-bec5-407d-8d5d-772ad12b7a07)
![image](https://github.com/AstrorEnales/blender_magicavoxel/assets/16767517/9f7ee81e-6fb5-462a-a54c-e6426ade95be)
The two models are just a reverse of the same model to better showcase the issue. 
The import settings I have set are visible below. 
![image](https://github.com/AstrorEnales/blender_magicavoxel/assets/16767517/c3845142-64ca-4e20-9872-bae2068c2919)
Please let me know if there is any additional information needed to debug this issue.

**Comment by AstrorEnales** [comment] 2024-06-25 05:05
Thank you for using the addon and your report!
To narrow down what the issue might be, can you make a screenshot of the uv unwrap by selecting all faces in edit mode in the uv editing tab and post it here?

**Comment by drca234** [comment] 2024-06-25 12:38
Yes, here's one for each of the imported models (bottom model first): 
![image](https://github.com/AstrorEnales/blender_magicavoxel/assets/16767517/f1d04266-d567-449e-a70e-9d3c503d2b49)
![image](https://github.com/AstrorEnales/blender_magicavoxel/assets/16767517/7bf6b8cf-8278-4a58-9c7f-6b167ebb4326)

**Comment by AstrorEnales** [comment] 2024-06-25 13:39
Thanks, i was able to reproduce the problem and will fix it asap. Will let you know when there is a new version!

**Comment by drca234** [comment] 2024-06-25 14:17
Thanks, I greatly appreciate it!

**Comment by AstrorEnales** [comment] 2024-06-27 08:37
The issue is now fixed and a new version is available [v1.5.5](https://github.com/AstrorEnales/blender_magicavoxel/releases/latest)!

**Closed as completed by AstrorEnales** 2024-06-27 08:37 UTC
